---
title: "heartfailure"
output: html_document
---

```{r}
data <- read.csv('data/heartfailure.csv', sep = ',')
dead <- data[data$DEATH_EVENT == 1,]
```

Podstawowe informacje o zbiorze danych:

Sprawdźmy histogram wieku pacjentów oraz zaznaczoną na nim liczbą wyników ataków serca zakończonych zgonem pacjenta:
```{r}
renderPlot({
  ggplot(data, aes(x = age)) +
    ggtitle('Wiek a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = creatinine_phosphokinase)) +
    ggtitle('Fosfokinaza kreatynowa a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = ejection_fraction)) +
    ggtitle('Frakcja wyrzutowa a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = high_blood_pressure)) +
    ggtitle('Wysokie ciśnienie krwi a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = platelets)) +
    ggtitle('Płytki krwi a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = serum_creatinine)) +
    ggtitle('Kreatynina a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = serum_sodium)) +
    ggtitle('Sód a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = smoking)) +
    ggtitle('Palenie a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```

```{r}
renderPlot({
  ggplot(data, aes(x = sex)) +
    ggtitle('Płeć a wystąpienie zgonu') +
    geom_histogram(data = data, fill = 'red', alpha = 0.4) +
    geom_histogram(data = dead, fill = 'blue', alpha = 0.4)
})
```
